// <auto-generated />
namespace N01520224_PassionProject_Reeservation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class guest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(guest));
        
        string IMigrationMetadata.Id
        {
            get { return "202206032223305_guest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
